if(EXISTS "/home/daniel/Рабочий стол/TCPChat/Server/UnitTests/UnitTests[1]_tests.cmake")
  include("/home/daniel/Рабочий стол/TCPChat/Server/UnitTests/UnitTests[1]_tests.cmake")
else()
  add_test(UnitTests_NOT_BUILT UnitTests_NOT_BUILT)
endif()
