add_test( ChatMemberTest.ChatMemberShouldBeNotAuthorized [==[/home/daniel/Рабочий стол/TCPChat/bin/UnitTests]==] [==[--gtest_filter=ChatMemberTest.ChatMemberShouldBeNotAuthorized]==] --gtest_also_run_disabled_tests)
set_tests_properties( ChatMemberTest.ChatMemberShouldBeNotAuthorized PROPERTIES WORKING_DIRECTORY [==[/home/daniel/Рабочий стол/TCPChat/Server/UnitTests]==] SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( ChatMemberTest.ChatMemberSetAuthorizedAndGetNick [==[/home/daniel/Рабочий стол/TCPChat/bin/UnitTests]==] [==[--gtest_filter=ChatMemberTest.ChatMemberSetAuthorizedAndGetNick]==] --gtest_also_run_disabled_tests)
set_tests_properties( ChatMemberTest.ChatMemberSetAuthorizedAndGetNick PROPERTIES WORKING_DIRECTORY [==[/home/daniel/Рабочий стол/TCPChat/Server/UnitTests]==] SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( SocketTest.SendDataToClient [==[/home/daniel/Рабочий стол/TCPChat/bin/UnitTests]==] [==[--gtest_filter=SocketTest.SendDataToClient]==] --gtest_also_run_disabled_tests)
set_tests_properties( SocketTest.SendDataToClient PROPERTIES WORKING_DIRECTORY [==[/home/daniel/Рабочий стол/TCPChat/Server/UnitTests]==] SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( SocketTest.AsyncReads [==[/home/daniel/Рабочий стол/TCPChat/bin/UnitTests]==] [==[--gtest_filter=SocketTest.AsyncReads]==] --gtest_also_run_disabled_tests)
set_tests_properties( SocketTest.AsyncReads PROPERTIES WORKING_DIRECTORY [==[/home/daniel/Рабочий стол/TCPChat/Server/UnitTests]==] SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( LoggerTest.InitTheLogger [==[/home/daniel/Рабочий стол/TCPChat/bin/UnitTests]==] [==[--gtest_filter=LoggerTest.InitTheLogger]==] --gtest_also_run_disabled_tests)
set_tests_properties( LoggerTest.InitTheLogger PROPERTIES WORKING_DIRECTORY [==[/home/daniel/Рабочий стол/TCPChat/Server/UnitTests]==] SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( LoggerTest.SendLog [==[/home/daniel/Рабочий стол/TCPChat/bin/UnitTests]==] [==[--gtest_filter=LoggerTest.SendLog]==] --gtest_also_run_disabled_tests)
set_tests_properties( LoggerTest.SendLog PROPERTIES WORKING_DIRECTORY [==[/home/daniel/Рабочий стол/TCPChat/Server/UnitTests]==] SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set( UnitTests_TESTS ChatMemberTest.ChatMemberShouldBeNotAuthorized ChatMemberTest.ChatMemberSetAuthorizedAndGetNick SocketTest.SendDataToClient SocketTest.AsyncReads LoggerTest.InitTheLogger LoggerTest.SendLog)
